services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - MONGO_URI=mongodb+srv://mokshmadaan27:EY5ThSRlNK7CtFYa@cluster0.tneeu6b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8001:8001"
    networks:
      - app-network
    depends_on:
      - mongodb
    env_file:
      - .env

  image-service:
    build:
      context: ./image-service
      dockerfile: Dockerfile
    container_name: image-service
    environment:
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - MONGO_URI=mongodb+srv://mokshmadaan27:EY5ThSRlNK7CtFYa@cluster0.tneeu6b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
    ports:
      - "8002:8001"
    networks:
      - app-network
    depends_on:
      - mongodb

  friendship-service:
    build:
      context: ./friendship-service
      dockerfile: Dockerfile
    container_name: friendship-service
    environment:
      - MONGO_URI=mongodb+srv://mokshmadaan27:EY5ThSRlNK7CtFYa@cluster0.tneeu6b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
    ports:
      - "8003:8001"
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_URI=mongodb+srv://mokshmadaan27:EY5ThSRlNK7CtFYa@cluster0.tneeu6b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
