apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: your-docker-repo/image-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: s3-bucket-name
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: aws-secret-access-key
            - name: AWS_REGION
              value: "us-east-1"
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  selector:
    app: image-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP
